### ISSUE TITLE
Library link update

### ISSUE THREAD

**Issue by santaimpersonator** [sparkfunX/Qwiic_Proximity_VCNL4040#1]
It looks like the library linked in the README.md is for the MS5637 Barometric Pressure. I think it needs to point to here: [https://github.com/sparkfun/SparkFun_VCNL4040_Arduino_Library](https://github.com/sparkfun/SparkFun_VCNL4040_Arduino_Library)

**Comment by nseidle** [comment]
Indeed! Thanks! Should be fixed now.
